#!/bin/bash
# Script 2: FOSS Package Inspector

PACKAGE="git"

# Check if package is installed
if dpkg -l | grep -q "^ii  $PACKAGE"; then
    echo "$PACKAGE is installed."
    dpkg -s $PACKAGE | grep -E 'Version|Maintainer|Description'
else
    echo "$PACKAGE is NOT installed."
fi

# Case statement
case $PACKAGE in
    git) echo "Git: Distributed version control system built for collaboration" ;;
    apache2) echo "Apache: Powers a large part of the internet" ;;
    mysql) echo "MySQL: Database used in millions of applications" ;;
    firefox) echo "Firefox: Open source browser promoting privacy" ;;
    *) echo "Unknown package" ;;
esac
